#!/bin/bash

# A simple script to display wifi name or ethernet connection status
# 'ssid -i' = with icon, 'ssid' = text only
# Cheers!
# Addy

# Set the path to iwgetid command
IWGETID_PATH=$(which iwgetid)

if [[ -z "${IWGETID_PATH}" ]]; then
  echo "iwgetid command not found"
  exit 1
fi

SSID_NAME=$(${IWGETID_PATH} -r)

if [[ "${SSID_NAME}" != "" ]]; then
  if  [[ $1 = "-i" ]]; then
    echo "  ${SSID_NAME}"
  else
    echo "${SSID_NAME}"
  fi
else
  # Detect Ethernet interface name
  ETH_INTERFACE=$(ip -o link show | awk '{print $2}' | grep -E '^e.*:' | tr -d ':')
  
  # Check for Ethernet connection
  if [[ -n "${ETH_INTERFACE}" && $(cat /sys/class/net/${ETH_INTERFACE}/operstate) == "up" ]]; then
    if [[ $1 = "-i" ]]; then
      echo "  ${ETH_INTERFACE}"
    else
      echo "${ETH_INTERFACE}"
    fi
  else
    echo "Not Connected"
  fi
fi

exit
