#!/bin/bash

case "$1" in
    configure)

      RUID=$(who | awk 'FNR == 1 {print $1}')

      if [ "$RUID" != "" ] ; then
        if [ ! -f /home/${RUID}/.config/autostart/hamonikr-theme.desktop ] ; then
          [ ! -d "/home/${RUID}/.config/autostart/" ] && mkdir -p /home/${RUID}/.config/autostart/
          cp /etc/skel/.config/autostart/hamonikr-theme.desktop /home/${RUID}/.config/autostart/
          chown ${RUID}:${RUID} /home/${RUID}/.config/autostart -R
        fi

        if [ ! -f /home/${RUID}/.config/autostart/plank.desktop ] ; then
          [ ! -d "/home/${RUID}/.config/autostart/" ] && mkdir -p /home/${RUID}/.config/autostart/
          cp /etc/skel/.config/autostart/plank.desktop /home/${RUID}/.config/autostart/
          chown ${RUID}:${RUID} /home/${RUID}/.config/autostart -R

          [ ! -d "/home/${RUID}/.config/plank/dock1/launchers/" ] && mkdir -p /home/${RUID}/.config/plank/dock1/launchers/
          cp /etc/skel/.config/plank/dock1/launchers/*.dockitem /home/${RUID}/.config/plank/dock1/launchers/
          chown ${RUID}:${RUID} /home/${RUID}/.config/plank -R          
        fi
      fi
      
      gtk-update-icon-cache || true
      fc-cache -f

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0