#!/bin/bash

case "$1" in
    configure)

      RUID=$(who | awk 'FNR == 1 {print $1}')

      if [ "$RUID" != "" ] ; then
        if [ ! -f /home/${RUID}/.config/autostart/hamonikr-theme.desktop ] ; then
          cp /etc/skel/.config/autostart/hamonikr-theme.desktop /home/${RUID}/.config/autostart/
        fi

        if [ ! -f /home/${RUID}/.config/autostart/plank.desktop ] ; then
          cp /etc/skel/.config/autostart/plank.desktop /home/${RUID}/.config/autostart/
        fi

        rm -f /home/${RUID}/.hamonikr/themes/done/hamonikr-theme-start.* || true
        rm -f /home/${RUID}/.hamonikr/themes/save/hamonikr-theme-backup.dconf || true
      fi

      if [ -f "/etc/hamonikr/info" ] ; then

          if [ -f /usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-override.json ] ; then
            cp -f /usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-override.json \
            /usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-override.json.bak

            cp -f /usr/share/hamonikr/applets/grouped-window-list@cinnamon.org/settings-override.json \
            /usr/share/cinnamon/applets/grouped-window-list@cinnamon.org/settings-override.json
          fi

          if [ -f /usr/share/cinnamon/applets/menu@cinnamon.org/settings-override.json ] ; then
            cp -f /usr/share/cinnamon/applets/menu@cinnamon.org/settings-override.json \
            /usr/share/cinnamon/applets/menu@cinnamon.org/settings-override.json.bak

            cp -f /usr/share/hamonikr/applets/menu@cinnamon.org/settings-override.json \
            /usr/share/cinnamon/applets/menu@cinnamon.org/settings-override.json
          fi

          cp -f /usr/share/hamonikr/gschema/hamonikr-system.gschema.override /usr/share/glib-2.0/schemas/hamonikr-system.gschema.override
          
          if which glib-compile-schemas >/dev/null 2>&1 ; then
              glib-compile-schemas /usr/share/glib-2.0/schemas
          fi    
          echo "Update hamonikr-system gschema"
      fi

      gtk-update-icon-cache || true

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0