#!/bin/bash

case "$1" in
    configure)

      # Get Real User ID
      RUID=$(who | awk 'FNR == 1 {print $1}')
      # Get Real User UID
      RUSER_UID=$(id -u ${RUID})

      if [ "$RUID" != "" ] ; then
        if [ ! -f /home/${RUID}/.config/autostart/hamonikr-theme.desktop ] ; then
          [ ! -d "/home/${RUID}/.config/autostart/" ] && mkdir -p /home/${RUID}/.config/autostart/
          cp /etc/skel/.config/autostart/hamonikr-theme.desktop /home/${RUID}/.config/autostart/
          chown ${RUID}:${RUID} /home/${RUID}/.config/autostart -R
        fi

        if [ ! -f /home/${RUID}/.config/autostart/plank.desktop ] ; then
          [ ! -d "/home/${RUID}/.config/autostart/" ] && mkdir -p /home/${RUID}/.config/autostart/
          cp /etc/skel/.config/autostart/plank.desktop /home/${RUID}/.config/autostart/
          chown ${RUID}:${RUID} /home/${RUID}/.config/autostart -R

          [ ! -d "/home/${RUID}/.config/plank/dock1/launchers/" ] && mkdir -p /home/${RUID}/.config/plank/dock1/launchers/
          cp /etc/skel/.config/plank/dock1/launchers/*.dockitem /home/${RUID}/.config/plank/dock1/launchers/
          chown ${RUID}:${RUID} /home/${RUID}/.config/plank -R          
        fi
      fi

      if [ ! -z "$RUID" ] ; then
          sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" dconf load /org/gnome/terminal/legacy/profiles:/:$(gsettings list-recursively org.gnome.Terminal.ProfilesList | grep default | cut -d' ' -f3 | tr -d "'")/ < /usr/share/hamonikr-themes/gnome-terminal.dconf
      fi

      gtk-update-icon-cache || true
      fc-cache -f

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    triggered)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0