#!/bin/bash

case "$1" in
    remove|upgrade)

      RUID=$(who | awk 'FNR == 1 {print $1}')
      [ -d /home/${RUID}/.hamonikr/theme ] && rm -rf /home/${RUID}/.hamonikr/theme
      [ ! -z $(pidof plank | grep '[0-9]') ] && killall plank
      [ -f /home/${RUID}/.config/autostart/plank.desktop ] && rm /home/${RUID}/.config/autostart/plank.desktop

      gtk-update-icon-cache || true

      update-rc.d -f hamonikr-system remove
      if which systemctl >/dev/null 2>&1
      then
          systemctl daemon-reload
      fi
    ;;
    deconfigure|failed-upgrade)
      gtk-update-icon-cache || true
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
