#!/bin/sh
# prerm script for ldm-themes
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|deconfigure|failed-upgrade)

      # fc-cache -v -f

      /usr/local/bin/hamonikr-theme-start restore

    ;;

    upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0