#!/bin/sh
# prerm script for ldm-themes
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove)
      /usr/local/bin/hamonikr-theme-start restore
      gtk-update-icon-cache || true
    ;;

    deconfigure|failed-upgrade)
      gtk-update-icon-cache || true
      # fc-cache -v -f
    ;;

    upgrade)
      gtk-update-icon-cache || true    
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0